import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Silver Creek Logistics LLC aggregate delivery services.",
};

export default function TermsPage() {
  const effective = "May 1, 2025";

  return (
    <div className="bg-white">
      <div className="bg-[#1a2744] text-white py-12">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-extrabold mb-2">Terms of Service</h1>
          <p className="text-gray-400 text-sm">Effective date: {effective}</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 prose prose-gray max-w-none">
        <div className="space-y-8 text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">1. Agreement to Terms</h2>
            <p>
              By contacting Silver Creek Logistics LLC ("Company," "we," "us," or "our") to request a delivery,
              submitting a quote request through our website, or accepting delivery of materials, you agree to these
              Terms of Service. If you do not agree, do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">2. Services</h2>
            <p>
              Silver Creek Logistics LLC provides aggregate hauling and delivery services including, but not limited to,
              topsoil, fill dirt, road base, pit run, sand, gravel, pea gravel, and rip rap. We operate within
              approximately 50 miles of Twin Falls, Idaho. Service availability is subject to material availability,
              truck availability, and weather conditions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">3. Quotes and Pricing</h2>
            <p>
              All quotes provided via our website calculator, phone, or email are estimates only and are not binding
              until confirmed in writing by Silver Creek Logistics LLC. Prices are subject to change without notice due
              to fuel costs, material pricing, and market conditions. A confirmed quote is valid for 48 hours unless
              otherwise stated.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">4. Orders and Payment</h2>
            <p>
              Orders are accepted by phone or via our contact form. Payment terms will be communicated at the time of
              order confirmation. We reserve the right to require a deposit for large or long-distance orders. Payment
              is due upon delivery unless otherwise agreed in writing.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">5. Delivery</h2>
            <p>
              Customer is responsible for ensuring that the delivery site is accessible by our vehicles (Mack super dump
              or side dump). Silver Creek Logistics LLC is not responsible for damage to private driveways, roads,
              landscaping, or other property caused by normal delivery operations. Customer must designate a safe drop
              location prior to delivery. We reserve the right to refuse delivery to sites deemed unsafe for our
              equipment or personnel.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">6. Cancellations and Rescheduling</h2>
            <p>
              Cancellations made less than 24 hours before a scheduled delivery may be subject to a cancellation fee of
              up to $85. Rescheduling requests should be made as early as possible and are subject to availability.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">7. Material Quantities</h2>
            <p>
              All quantity estimates, including those generated by our material calculator, are approximate. Actual
              quantity delivered is determined by load weight and may vary. We recommend ordering 10–15% overage for
              compaction and waste. Silver Creek Logistics LLC is not responsible for project shortfalls due to
              inaccurate quantity estimates provided by the customer.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, Silver Creek Logistics LLC shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues,
              whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses.
              Our total liability for any claim arising from our services shall not exceed the amount paid by the
              customer for the specific delivery giving rise to the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">9. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Idaho, without regard to its conflict of law
              provisions. Any disputes shall be resolved in the courts of Twin Falls County, Idaho.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">10. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Updated terms will be posted on this page with a
              revised effective date. Continued use of our services after any changes constitutes acceptance of the new
              terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">11. Contact</h2>
            <p>
              Questions about these Terms of Service may be directed to Silver Creek Logistics LLC by phone or email as
              listed on our <a href="/contact" className="text-[#e8600a] hover:underline">Contact page</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
