import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "Disclaimer for Silver Creek Logistics LLC website and material calculator.",
};

export default function DisclaimerPage() {
  return (
    <div className="bg-white">
      <div className="bg-[#1a2744] text-white py-12">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-extrabold mb-2">Disclaimer</h1>
          <p className="text-gray-400 text-sm">Last updated: May 1, 2025</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="space-y-8 text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">General Information</h2>
            <p>
              The information provided on silvercreeklogistics.com is for general informational purposes only. All
              information on the site is provided in good faith, however we make no representation or warranty of any
              kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or
              completeness of any information on the site.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">Pricing Information</h2>
            <p>
              All prices listed on this website — including those shown on the pricing page and generated by the
              material calculator — are estimates only. Prices are subject to change without notice based on market
              conditions, material availability, fuel costs, and delivery distance. Listed prices do not constitute a
              binding offer. A confirmed written quote from Silver Creek Logistics LLC is required to establish a
              binding price.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">Material Calculator</h2>
            <p>
              The material calculator tool is provided as a convenience to help customers estimate their material needs.
              Results are approximations based on standard density factors and geometric formulas. Actual material
              requirements may vary based on soil conditions, compaction, waste factors, and other site-specific
              variables. Silver Creek Logistics LLC is not responsible for project outcomes based on calculator
              estimates. We recommend consulting with a licensed contractor for critical applications.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">Professional Advice</h2>
            <p>
              Nothing on this website constitutes professional engineering, agricultural, or construction advice. For
              projects requiring precise specifications — including roadways, structural fills, or projects subject to
              local building codes — please consult a qualified professional.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">External Links</h2>
            <p>
              This website may contain links to external websites. These links are provided for informational purposes
              only. Silver Creek Logistics LLC has no control over the content, privacy policies, or practices of any
              third-party websites and accepts no responsibility for them.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">Delivery and Service Availability</h2>
            <p>
              Service availability, material availability, and delivery scheduling are subject to change based on
              operational capacity, weather, equipment maintenance, and other factors. Silver Creek Logistics LLC
              reserves the right to decline any order.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1a2744] mb-3">Contact</h2>
            <p>
              For questions, contact us via our{" "}
              <a href="/contact" className="text-[#e8600a] hover:underline">Contact page</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
